#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,nvim,wezterm,opencode"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dot-config
fi

pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"

    # Special handling for spesific folders 
    if [[ "$folder" == "opencode" ]]; then
        stow -D --target=$HOME/.config/opencode --verbose $folder
        stow --target=$HOME/.config/opencode --verbose $folder
    else
        # Use default target from .stowrc (~/.config)
        stow -D --verbose $folder
        stow --verbose $folder
    fi
done

popd
