#!/bin/bash

# by default, tile all windows
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# config for new tab on terminal. 
yabai -m signal --add app='^Ghostty$' event=window_created   action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

# Disable for spesific app 
yabai -m rule --add app="^System Settings$" manage=off 
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Dota 2$" manage=off
yabai -m rule --add app="^MetaMask$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^freewrite$" manage=off

